export const ROLE_PERMISSIONS = {
  superadmin: {
    dashboard: true,
    tenants: { view: true, create: true, edit: true, delete: true },
    users: { view: true, edit: true, toggleActive: true },
    doctors: { view: true, create: true, edit: true, invite: true },
    bookings: { view: true, create: true, cancel: true },
    clinicalRecords: { view: true, create: true, edit: true, delete: true },
    billing: { view: true, create: true, edit: true, delete: true },
    laboratory: { view: true, create: true, edit: true },
    analytics: { view: true },
    audit: { view: true },
    specialties: { view: true, create: true, edit: true, delete: true },
    saas: { view: true, manage: true },
    prescriptions: { view: true, create: true, edit: true, delete: true },
    scheduling: { view: true, create: true, edit: true, delete: true },
    availability: { view: true, create: true, delete: true },
    medicalHistory: { view: true },
    reports: { view: true },
    settings: { view: true, edit: true },
    notifications: { view: true },
  },
  admin: {
    dashboard: true,
    users: { view: true, edit: true, toggleActive: true },
    doctors: { view: true, create: true, invite: true },
    bookings: { view: true, create: true, cancel: true },
    clinicalRecords: { view: true },
    billing: { view: true, create: true, edit: true, delete: true },
    laboratory: { view: true, create: true, edit: true },
    analytics: { view: true },
    audit: { view: true },
    specialties: { view: true, create: true, edit: true, delete: true },
    prescriptions: { view: true, create: true, edit: true, delete: true },
    scheduling: { view: true, create: true, edit: true, delete: true },
    availability: { view: true, create: true, delete: true },
    patients: { view: true },
    medicalHistory: { view: true, create: true, edit: true },
    reports: { view: true },
    settings: { view: true, edit: true },
    notifications: { view: true },
  },
  doctor: {
    dashboard: true,
    bookings: { view: true },
    availability: { view: true, create: true, delete: true },
    clinicalRecords: { view: true, create: true, edit: true, delete: true },
    prescriptions: { view: true, create: true, edit: true, delete: true },
    laboratory: { view: true, validate: true, sign: true },
    analytics: { myStats: true },
    medicalHistory: { view: true, create: true, edit: true },
    patients: { view: true },
    scheduling: { view: true },
    reports: { view: true },
    settings: { view: true },
    notifications: { view: true },
  },
  lab_technician: {
    dashboard: true,
    laboratory: { view: true, create: true, edit: true, validate: true, deliver: true },
    reports: { view: true },
    notifications: { view: true },
  },
  patient: {
    dashboard: true,
    bookings: { view: true, create: true, cancel: true },
    clinicalRecords: { view: true },
    laboratory: { view: true },
    prescriptions: { view: true },
    medicalHistory: { view: true },
    settings: { view: true, edit: true },
    notifications: { view: true },
  },
  guest: {
    bookings: { create: true, view: true, cancel: true },
  },
  user: {
    dashboard: true,
    settings: { view: true, edit: true },
  },
} as const;

export type RolePermissions = typeof ROLE_PERMISSIONS;
